const prompts = [
  "Market overview?",
  "What is the current trend?",
  "Companies to look out for?",
  "What crypto should I buy?",
  "How is Bitcoin performing?",
  "What are the top 5 cryptocurrencies today?",
  "What is Ethereum's price prediction?",
  "Should I invest in Dogecoin?",
  "What are the risks of investing in crypto?",
  "How does blockchain technology work?",
  "What is the difference between Bitcoin and Ethereum?",
  "What are the latest crypto regulations?",
  "How can I start mining cryptocurrency?",
  "What is the best wallet for storing crypto?",
  "What is the current market cap of Bitcoin?",
  "How is Solana performing?",
  "What are the benefits of staking crypto?",
  "What is the future of NFTs?",
  "How does DeFi work?",
  "What are the top decentralized exchanges?",
  "What is the best strategy for day trading crypto?",
  "How do I secure my cryptocurrency wallet?",
  "What are the environmental impacts of Bitcoin mining?",
  "What is the difference between proof of work and proof of stake?",
  "What are the top crypto trends for this year?",
  "How do I calculate crypto taxes?",
  "What are the best crypto exchanges for beginners?",
  "What is the history of Bitcoin?",
  "How does smart contract technology work?",
  "What are the risks of using decentralized exchanges?",
  "What is the future of blockchain in finance?",
  "How can I identify a crypto scam?",
  "What are the benefits of using stablecoins?",
  "What is the role of crypto in the metaverse?",
  "How does tokenomics affect a cryptocurrency's value?",
  "What are the top Layer 2 solutions for Ethereum?",
  "What is the Lightning Network?",
  "How do I participate in a crypto airdrop?",
  "What are the best practices for long-term crypto investment?",
  "What is the difference between altcoins and tokens?",
  "How does yield farming work?",
  "What are the top privacy-focused cryptocurrencies?",
  "What is the role of oracles in blockchain?",
  "How do I analyze a crypto project's whitepaper?",
  "What is the importance of liquidity in crypto markets?",
  "What is the difference between centralized and decentralized finance?",
  "How do I use a hardware wallet?",
  "What are the top crypto influencers to follow?",
  "What is the impact of regulations on crypto markets?",
  "How do I create my own cryptocurrency?",
];

export default prompts;
